# Generated by Django 3.1 on 2020-08-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('beta_mode', models.BooleanField(default=False)),
                ('site_name', models.CharField(default='Camel Cart', max_length=255)),
                ('site_logo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('site_message', models.CharField(blank=True, default='Welcome to Quezon Agrimart!', max_length=125, null=True)),
                ('phone', models.CharField(default='', max_length=55)),
                ('email', models.EmailField(default='', max_length=55)),
                ('location', models.CharField(default='', max_length=100)),
                ('office_hours', models.CharField(default='', max_length=100)),
                ('about_sub_header', models.CharField(default='Insert Sub Header Here', max_length=55)),
                ('about_text', models.TextField(default='Insert About Text Here', max_length=4000)),
                ('standard_delivery_price', models.PositiveIntegerField(default=50)),
                ('pickup_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
