# Generated by Django 3.1.1 on 2020-09-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='standard_delivery_price',
            new_name='delivery_price',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='about_sub_header',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='pickup_enabled',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='site_logo',
        ),
    ]
