# Generated by Django 3.1.1 on 2020-09-10 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20200910_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='office_hours',
        ),
    ]
