# Generated by Django 3.1.1 on 2020-09-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_remove_siteconfiguration_office_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='delivery_price',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='per_km_price',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_message',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
