# Generated by Django 3.1.1 on 2020-11-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_auto_20200912_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='Trike', max_length=255),
        ),
    ]
