# Generated by Django 3.1.1 on 2020-11-30 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_auto_20201201_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='motorcycle_per_km_price',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='tricycle_per_km_price',
        ),
    ]
