# Generated by Django 3.1.1 on 2020-12-02 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_auto_20201201_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='rider_commission',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
