# Generated by Django 3.1.1 on 2020-12-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_siteconfiguration_shipping_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='two_way_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
