# Generated by Django 3.1.1 on 2020-09-11 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='cod',
            new_name='payment_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='pickup',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='shipping',
        ),
        migrations.AddField(
            model_name='activity',
            name='contact',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='email',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='first_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='gender',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='height',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='last_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='length',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='loc1_address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='loc2_address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='width',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='loc2_latitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='loc2_longitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.user'),
            preserve_default=False,
        ),
    ]
