# Generated by Django 3.1.1 on 2020-09-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20200911_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='distance_text',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='distance_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration_text',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
