# Generated by Django 3.1.1 on 2020-09-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_auto_20200911_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='loc1_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='loc1_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='loc2_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='loc2_longitude',
            field=models.IntegerField(default=0),
        ),
    ]
