# Generated by Django 3.1.1 on 2020-09-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_auto_20200912_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='payment_type',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
