# Generated by Django 3.1.1 on 2020-09-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_auto_20200912_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='loc1_latitude',
            field=models.CharField(blank=True, max_length=91, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='loc1_longitude',
            field=models.CharField(blank=True, max_length=91, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='loc2_latitude',
            field=models.CharField(blank=True, max_length=91, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='loc2_longitude',
            field=models.CharField(blank=True, max_length=91, null=True),
        ),
    ]
