# Generated by Django 3.1.1 on 2020-09-14 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_auto_20200912_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.seller'),
        ),
    ]
