# Generated by Django 3.1.1 on 2020-09-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_auto_20200915_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Sample food description', max_length=4000),
        ),
    ]
