# Generated by Django 3.1.1 on 2020-09-19 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_auto_20200917_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('description', models.TextField(default='Sample food description', max_length=4000)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('sale_price_start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('sale_price_end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('date_published', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price_end_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price_start_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
    ]
