# Generated by Django 3.1.1 on 2020-09-19 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_auto_20200919_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Sample food description', max_length=4000),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='logistics.product'),
            preserve_default=False,
        ),
    ]
