# Generated by Django 3.1.1 on 2020-09-19 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0015_auto_20200919_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Order',
        ),
        migrations.RemoveField(
            model_name='item',
            name='activity',
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='logistics.order'),
            preserve_default=False,
        ),
    ]
