# Generated by Django 3.1.1 on 2020-09-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_auto_20200919_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
