# Generated by Django 3.1.1 on 2020-09-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_order_order_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
