# Generated by Django 3.1.1 on 2020-09-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0018_auto_20200920_0748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='OrderItem',
        ),
    ]
