# Generated by Django 3.1.1 on 2020-09-20 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0019_auto_20200920_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='logistics.productvariant'),
            preserve_default=False,
        ),
    ]
