# Generated by Django 3.1.1 on 2020-09-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0020_auto_20200920_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
