# Generated by Django 3.1.1 on 2020-09-22 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0021_auto_20200921_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='distance_text',
        ),
        migrations.RemoveField(
            model_name='order',
            name='distance_value',
        ),
        migrations.RemoveField(
            model_name='order',
            name='duration_text',
        ),
        migrations.RemoveField(
            model_name='order',
            name='duration_value',
        ),
        migrations.RemoveField(
            model_name='order',
            name='loc1_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='loc1_latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='loc1_longitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='loc2_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='loc2_latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='loc2_longitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='store',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='logistics.order'),
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc1_latitude', models.CharField(max_length=91)),
                ('loc1_longitude', models.CharField(max_length=91)),
                ('loc1_address', models.CharField(max_length=225)),
                ('loc2_latitude', models.CharField(max_length=91)),
                ('loc2_longitude', models.CharField(max_length=91)),
                ('loc2_address', models.CharField(max_length=225)),
                ('distance_text', models.CharField(max_length=55)),
                ('distance_value', models.PositiveIntegerField(default=0)),
                ('duration_text', models.CharField(max_length=55)),
                ('duration_value', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journies', to='logistics.order')),
            ],
        ),
    ]
