# Generated by Django 3.1.1 on 2020-09-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0022_auto_20200922_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='logistics.order'),
        ),
    ]
