# Generated by Django 3.1.1 on 2020-09-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0023_auto_20200922_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='loc1_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='loc1_longitude',
            new_name='longitude',
        ),
    ]
