# Generated by Django 3.1.1 on 2020-09-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0024_auto_20200924_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance_text',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='duration_text',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='duration_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='loc1_address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='loc1_latitude',
            field=models.CharField(blank=True, max_length=91, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='loc1_longitude',
            field=models.CharField(blank=True, max_length=91, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='loc2_address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='loc2_latitude',
            field=models.CharField(blank=True, max_length=91, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='loc2_longitude',
            field=models.CharField(blank=True, max_length=91, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
