# Generated by Django 3.1.1 on 2020-09-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0025_auto_20200925_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journey',
        ),
    ]
