# Generated by Django 3.1.1 on 2020-09-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0027_auto_20200925_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
