# Generated by Django 3.1.1 on 2020-10-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0031_order_date_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_claimed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
