# Generated by Django 3.1.1 on 2020-10-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0032_order_date_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_pickedup',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_pickedup',
            field=models.BooleanField(default=False),
        ),
    ]
