# Generated by Django 3.1.1 on 2020-10-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0033_auto_20201011_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date_pickedup',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_pickedup',
            field=models.BooleanField(default=False),
        ),
    ]
