# Generated by Django 3.1.1 on 2020-10-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0034_auto_20201012_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='logistics.orderitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderreview',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='logistics.order'),
            preserve_default=False,
        ),
    ]
