# Generated by Django 3.1.1 on 2020-10-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0036_auto_20201013_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='logistics.orderitem'),
        ),
    ]
