# Generated by Django 3.1.1 on 2020-10-14 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0037_auto_20201014_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreview',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='logistics.order'),
        ),
    ]
