# Generated by Django 3.1.1 on 2020-11-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0040_auto_20201108_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_canceled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
