# Generated by Django 3.1.1 on 2020-11-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0041_auto_20201118_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
