# Generated by Django 3.1.1 on 2020-11-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0042_order_ordered_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider_payment_needed',
            field=models.BooleanField(default=False),
        ),
    ]
