# Generated by Django 3.1.1 on 2020-11-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0048_auto_20201201_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='per_km_price',
            field=models.PositiveIntegerField(default=35),
        ),
    ]
