# Generated by Django 3.1.1 on 2020-12-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0049_vehicle_per_km_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='two_way',
            field=models.BooleanField(default=False),
        ),
    ]
