# Generated by Django 3.1.1 on 2020-12-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0052_order_ordered_shipping_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionpayment',
            name='description',
            field=models.TextField(default='Insert About Text Here', max_length=4000),
        ),
    ]
