# Generated by Django 3.1.1 on 2020-12-02 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0053_commissionpayment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionpayment',
            name='date_paid',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
