# Generated by Django 3.1.1 on 2020-12-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0059_auto_20201213_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='contact',
        ),
    ]
