# Generated by Django 3.1.1 on 2021-02-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0061_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='delivery_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='order_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
    ]
