# Generated by Django 3.1.1 on 2021-02-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0062_auto_20210218_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(default=2, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
