# Generated by Django 3.1.1 on 2021-02-22 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0066_remove_promocode_order_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissionpayment',
            old_name='rider',
            new_name='partner',
        ),
    ]
