# Generated by Django 3.1.1 on 2021-03-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0067_auto_20210222_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
