# Generated by Django 3.1.1 on 2021-03-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0069_auto_20210317_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
