# Generated by Django 3.1.1 on 2021-03-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0070_promocode_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
