# Generated by Django 3.1.1 on 2020-11-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='drivers_license',
            field=models.ImageField(blank=True, null=True, upload_to='photos/license'),
        ),
    ]
