# Generated by Django 3.1.1 on 2020-11-15 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contact_drivers_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='drivers_license',
            field=models.ImageField(blank=True, null=True, upload_to='photos/license/'),
        ),
    ]
