# Generated by Django 3.1.1 on 2020-11-18 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201115_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(55)]),
        ),
    ]
