# Generated by Django 3.1.1 on 2020-09-09 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200909_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_region',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_zipcode',
        ),
    ]
