# Generated by Django 3.1.1 on 2020-10-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200928_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=55, unique=True),
            preserve_default=False,
        ),
    ]
