# Generated by Django 3.1.1 on 2020-11-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201012_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plate_number',
            field=models.CharField(blank=True, max_length=55, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='photos/profile_pictures/%Y/%m/%d/'),
        ),
    ]
