# Generated by Django 3.1.1 on 2020-11-30 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0048_auto_20201201_0731'),
        ('accounts', '0012_auto_20201109_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='logistics.vehicle'),
        ),
    ]
