# Generated by Django 3.1.1 on 2021-02-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0063_auto_20210221_1618'),
        ('accounts', '0016_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promo_codes_used',
            field=models.ManyToManyField(to='logistics.PromoCode'),
        ),
    ]
