# Generated by Django 3.1.1 on 2021-02-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0065_auto_20210222_0704'),
        ('accounts', '0017_user_promo_codes_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='promo_codes_used',
            field=models.ManyToManyField(blank=True, null=True, to='logistics.PromoCode'),
        ),
    ]
