import React, { Fragment } from 'react'
import { HashLink as Link } from 'react-router-hash-link';

import ArticleNav from '../ArticleNav'

import { connect } from 'react-redux';


const TermsAndConditions = ({}) => {
  
  return (
    <Fragment>
      <ArticleNav/>
      <section className="section section-about">
        <div className="container">
          <div className="row">
            <div className="col s12">
              <h4 className="fw-6">Terms and Conditions of the Special Contract of Private Carriage of Goods Between User and Participating Driver</h4>
              <p>The User, by the submission of its Order using the Software and the acceptance of the computation provided by TRIKE of the fees and charges for said Order; and The Participating Driver, by its acceptance of the Order; hereby agree to be bound by this special contract of private carriage of goods (the "Contract"), subject to the terms and conditions hereinafter provided:</p>
            </div>
          </div>
          <div className="row">
            <div className="col s12">
              <h5 className="fw-6">1. Definitions and Interpretation</h5>
              <p>1.1 Capitalized terms used in this Contract shall bear the meaning provided under the User's Terms and Conditions, and/or the Participating Driver's Terms and Conditions.</p>
              <p>1.2 In case of conflict between the provisions of this Contract and the User's/ Participating Driver's Terms and Conditions, the rights, duties and obligations and remedies between the User and Participating Driver shall be governed by this Contract.</p>
            </div>
          </div>
          <div className="row">
            <div className="col s12">
              <h5 className="fw-6">2. Special Contract of Private Carriage of Goods</h5>
              <p>2.1. This Contract shall take effect between the User and the Participating Driver upon the acceptance by the Participating Driver of the User's Order.</p>
              <p>2.2 For and in consideration of the payment by the User of the fees and charges as computed through the Software, the Participating Driver shall provide the Private Carrier Services for the account of the User in accordance with the terms indicated by the User in the Order</p>
              <p>2.3 The User shall pay the Participating Drivers in accordance with the agreed mode of payment selected through the Software upon submission of the Order.</p>
              <p>2.4 No cancellation fees are chargeable as long as an Order is cancelled and communicated within sixty (60) minutes before the start of the Order pickup time. In the event that the cancellation was made after the Order pickup time has started, User shall be charged with the Standard Transport Fee.</p>
              <p>2.5 It is expressly understood that this Contract exclusively covers the carriage of goods and does not extend to the carriage of persons. On a case-to-case basis, and subject to the sole discretion of the Participating Driver, the Participating Driver may allow persons to be transported as accompanying persons to  the Shipment upon the request of the User. The User expressly agrees that the incidental transportation of accompanying persons may be allowed by the Participating Driver as a mere accommodation and only in cases where the accompanying persons are necessary to minimize any risk of damage or loss to the Shipment. The User expressly assumes any and all liability arising from the transportation of accompanying persons by the Participating Driver.</p>
              <p>2.6 The User and the Participating Driver acknowledge that any payment to the Participating Driver is made exclusively for the provision of Private Carrier Services and does not cover services for carrying or transporting accompanying passengers.</p>
            </div>
          </div>
          <div className="row">
            <div className="col s12">
              <h5 className="fw-6">3. Participating Driver's Warranties; Duties and Obligations</h5>
              <p>3.1. The Participating Driver warrants that he is a duly licensed driver in accordance with the laws of the Philippines, and that he is the registered owner or the authorized driver of the delivery vehicle to be used in this Contract.</p>
              <p>3.2 The Participating Driver undertakes to personally execute the duties and obligations of the private carrier under this Contract.</p>
              <p>3.3 The Participating Driver represents and warrants to the User that he has the special skills, appropriate delivery vehicle and sufficient property to perform the Private Carrier Services under this Contract and in accordance with the instructions of the User as indicated in the Order.</p>
              <p>3.4 The Participating Driver undertakes to faithfully comply with the Participating Driver's Code of Conduct and with the terms and conditions of this Contract.</p>
              <p>3.5 The Participating Driver shall provide any additional manpower requirements as may be indicated in the Order, and shall exercise direct supervision and control over the acts and services performed by the additional personnel provided by him.</p>
              <p>3.6 The Participating Driver shall provide due compensation to the additional personnel which he contracts to provide assistance to him in fulfilling the Order, and shall comply with all applicable laws in dealing with his assistants.</p>
              <p>3.7 The Participating Driver agrees that he may be reported by the User to TRIKE for any violation of this Contract, and after due inquiry by TRIKE, may be penalized for his violation of the terms and conditions of this Contract and that he may be off-boarded from the Software as a consequence thereof.</p>
              <p>3.8 The Participating Driver warrants that he is not engaged in the business of a public utility or a common carrier, and that he is not an employee, representative, agent, principal or officer of TRIKE.</p>
              <p>3.9 The Participating Driver shall refuse any Shipment that is or appears to be prohibited by law, dangerous or hazardous materials or substances, and radioactive material, or which may be harmful to the Participating Driver or the delivery vehicle.</p>
              <p>3.10 The Participating Driver shall exercise the diligence of a good father of the family to transmit the Shipment. He shall take reasonable precaution to prevent unauthorized persons from accessing the Shipment. He shall take reasonable precaution against loss of or damage to the Shipment while in transit.</p>
              <p>3.11 The Participating Driver shall use reasonable effort to deliver the Shipment according to the instructions of the User and the estimated time of arrival. Participating Drivers shall not be liable (whether in contract, tort or otherwise) for any delays in effecting delivery thereof for whatever reasons, unless the delay is directly caused by the gross negligence or fault of the Participating Driver.</p>
              <p>3.12 The Participating Driver shall not be liable for any loss or damage arising from or in connection with the  User's violations of warranties and obligations as stated in the User's Terms and Conditions or in this Contract.</p>
              <p>3.13 The Participating Driver shall not be liable for any delay in delivery of the Shipment, loss or damage due to force majeure, or any acts or omissions of any party other than the Participating Driver or his agents/assistants.</p>
              <p>3.14 The Participating Driver expressly consents to the collection, processing, storage and disclosure of personal information as may be necessary for the performance of his undertakings under this Contract. Specifically, the Participating Driver also expressly consents to the collection, processing, storage and disclosure of his personal information insofar as may be necessary for consumer complaint resolutions and resolution of other legal actions, whether administrative, civil or criminal. All other lawful criteria for the processing, use and disclosure of personal information of the Participating Driver under the Philippine Data Privacy Act (Republic Act No. 10173) are hereby incorporated in this agreement.</p>
              <p>3.15 The Participating Driver warrants and represents that he/she has all the legal requirements, licenses, government approvals, government permits, mandatory government registrations, government consent, government notices, among others, including regular/ periodic compliance with pertinent government regulations, including but not limited to the Securities and Exchange Commission, Department of Trade and Industry, Bureau of Internal Revenue, Social Security System, Home Development Mutual Fund, Philippine Health Insurance Corporation, local government units (including the Mayor's Office and the barangay), Department of Information and Communication Technologies, Land Transportation Office, Department of Transportation, and other applicable government agencies, in order to perform his/her contractual obligations herein. The Participating Driver acknowledges that TRIKE may rely on such warranty and representation without the need of documentary proof of the foregoing. The Participating Driver releases TRIKE from any liability, damage or claim that may result from the Participating Driver's misrepresentation or violation of warranty, as set forth in this section.</p>
              <p>3.16 The Participating Driver hereby expressly waives any claim, right of action or cause of action against TRIKE for damages, losses, death, or physical injuries, to the Participant Driver's own person or to third persons, arising from accidents, fortuitous events, and other unforeseen events during the course of performance of the contractual obligations herein. The Participant Driver acknowledges that he/she is independently operating on his/her own judgment in the course of performing his/her service, without control by TRIKE over the means and methods of his/her work. The Participant Driver assumes the risks arising from such unforeseen events. The  Participating Driver releases TRIKE from any liability, damage or claim that may result from such losses, damages, death, or physical injuries.</p>
            </div>
          </div>
          <div className="row">
            <div className="col s12">
              <h5 className="fw-6">4. User's Warranties; Duties and Obligations</h5>
              <p>4.1. The User warrants that he has the legal capacity to enter into this Contract under Philippine laws.</p>
              <p>4.2 The User conclusively agrees that the Private Carrier Services to be provided by the Participating Driver shall be subject to this Contract.</p>
              <p>4.3 The User acknowledges and agrees that the Participating Driver is a private carrier, and is not a public utility or a common carrier and thus, the rules pertaining to public utilities or common carriers shall have no application to this Contract.</p>
              <p>4.4 The User warrants that he has provided complete and accurate information in submitting the Order, such as the description of the delivery items included in the Shipment, his choice of delivery vehicle type, add-on services availed, and handling instructions of the Shipment, if any, through the Software, and agrees that the Participating Driver may rely upon the information provided by the User as true and correct without conducting an independent verification of the same.</p>
              <p>4.5 The User warrants to the Participating Driver that he is either the owner or the authorized agent of the owner of the Shipment, and that he is authorized to enter into this Contract not only for himself but also as agent for and on behalf of the owner of the Shipment.</p>
              <p>4.6 The User warrants that he has complied with all laws and regulations relating to the nature, condition, packing, handling, storage and carriage of the Shipment. User shall  not dispatch any articles that are prohibited by law, dangerous or hazardous materials or substances, radioactive material, or which may be harmful to the Participating Driver or the delivery vehicle.</p>
              <p>4.7 The User bears complete responsibility to ensure that the Shipment is adequately packed to protect against damage in the course of transit. It is conclusively presumed that the delivery items in the Shipment are inadequately packed if it appears to have been removed without the case, wrapper or container, or where the seal or packaging of the delivery items in the Shipment are torn or broken.</p>
              <p>4.8 The User agrees that Participating Driver is not obliged to open and inspect the Shipment, and that Participating Driver shall bear no responsibility or any legal liability resulting from the transportation of the Shipment.</p>
              <p>4.9 The User is liable for any loss or damage suffered by the Participating Driver or any third party as a result of User's violation/s of this Contract. </p>
              <p>4.10 The User agrees to hold the Participating Driver free and harmless from any legal liability to any third party as a result of any breach of the User's warranties, duties and obligations.</p>
              <p>4.11 The User agrees and undertakes to indemnify the Participating Driver against any and all assessments, liabilities, claims, suits, demands, damages, judgments, fees, costs, fines, penalties, interests and expenses of any nature whatsoever that the Participating Driver may suffer arising out of or in connection with the transportation of accompanying persons to the Shipment upon the request of the User.</p>
              <p>4.12 The User and Participating Driver agree that loss and damages to the Shipment shall be indemnified as follows: (i) if the loss or damage is due to the fault or negligence of the Participating Driver, the same shall be shouldered by the Participating Driver in his/her personal capacity, without recourse to TRIKE; (ii) if the loss or damage is due to the fault or negligence of the User (e.g., faulty packaging, delivery of spoiled goods), the same shall be shouldered by the User in his/her personal capacity, without recourse to the Participating Driver or to TRIKE; and (iii) if the loss or damage is due to fortuitous event or  other causes not due to the fault or negligence of the Participating Driver, the same shall be shouldered by the User in his/her personal capacity, without recourse to the Participating Driver or to TRIKE. User and Participating Driver agree and acknowledge that TRIKE is not a party to their private contract of carriage and, hence, is not liable for the breach of contract by the Participating Driver. However, TRIKE agrees to assume liability for the loss and damage in items (i) and (iii) of this clause, provided that there is an adequate consideration in the form of indemnity fee paid by the User at the time that he/she has availed of the services of the Participating Driver; provided, further, that the User discloses to TRIKE the declared value of the Shipment at the time of delivery, as well as consent and agree to the payment of the amount of indemnity fee as may be prescribed in the TRIKE application; provided, finally, that if the User does not provide the declared value of goods and does not pay adequate consideration in the form of prescribed indemnity fee, TRIKE shall not assume the liability for the loss or damage of the Shipment. User agrees and acknowledges that TRIKE's assumption of liability in item (i) and (iii) is an independent contractual arrangement between User and TRIKE which is supported by a separate consideration (i.e., indemnity fee), and does not arise from the private contract of carriage between the User and Participating Driver. User also acknowledges that the nature of this assumption of liability is that of a guarantee or surety as it is understood in the Philippine  Civil Code, in favor of the User as creditor and the Participating Driver as the debtor under the private contract of carriage. User acknowledges that entering into such arrangement with TRIKE for the indemnification for the loss or damage of the Shipment is optional on the part of the User, and hence User acknowledges that TRIKE is not principally engaged in the business of providing indemnity, surety or guarantee.</p>
            </div>
          </div>
          <div className="row">
            <div className="col s12">
              <h5 className="fw-6">5. Miscellaneous</h5>
              <p>5.1. <b>Participating Driver's Limited Liability</b>  The liability of the Participating Driver to the User for loss or destruction of the Shipment shall be limited to Two Thousand Pesos (PHP 2,000) only. The User shall bear the risk of loss if he avails of the Private Carrier Services for Shipments with a value exceeding this amount.</p>
              <p>5.2. <b>Entire agreement.</b> Both parties acknowledge that they have read this Contract, understood it and agreed to be bound by its terms and further agree that this Contract, together with the terms of the relevant Order, constitutes as the complete and exclusive statement of the agreement between the parties with respect to the subject matter hereof, which supersedes all proposals, and all other communications, regardless of the form  thereof, between the parties relating to the subject matter of this Contract. No representation, promise or inducement has been made by either party that is not  embodied in this Contract, and neither party shall be bound by or liable for any alleged representation, promise or inducement not otherwise contained in this Contract.</p>
              <p>5.4. <b>Venue of Action.</b>  In the event of any dispute, controversy, or claim arising from or relating to this Contract or the relevant Order, or the interpretation thereof, or any arrangements relating thereto or contemplated therein, or the breach, termination, or invalidity thereof, the parties hereto agree that venue shall be exclusively and properly set in the courts of Lucena City, Philippines.</p>
              <p>5.5. <b>Severality.</b> If any provision of this Contract is or becomes invalid, illegal or unenforceable, the remaining provisions shall remain in full force and effect, and for the invalid, illegal or unenforceable provision shall be substituted a valid, legal and enforceable provision which shall be as similar as possible in economic and business objectives as intended by the parties.</p>
              <p>5.6. <b>Reservation Clause.</b> TRIKE reserves the right to admit, maintain, retain, exclude, remove, suspend or block the User or Participating Driver in or from the use of the Software, including the right to change the status of such User or Participating Driver, for any reason  whatsoever which TRIKE may in its discretion decide based on its business judgment. Any action under this clause shall not give rise to any claim for compensation or damages by reason of such admission, maintenance, retention, exclusion, removal, suspension or blockage, or change of status thereof.</p>
            </div>
          </div>
        </div>
      </section>
    </Fragment>
  )
}

export default connect()(TermsAndConditions);